FROM ubuntu:20.04

ENV DEBIAN_FRONTEND="noninteractive"
ENV TZ="Asia/Taipei"

RUN apt-get update && \
    apt-get install -y apt-utils sudo git curl python3 vim locales

RUN DEBIAN_FRONTEND="noninteractive" TZ="Asia/Taipei" apt-get -qqy install tzdata
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install keyboard-configuration

# Install necessary packages
COPY install_noetic.sh /tmp
RUN /tmp/install_noetic.sh
COPY install_foxy.sh /tmp
RUN /tmp/install_foxy.sh
COPY install_dep.sh /tmp
RUN /tmp/install_dep.sh
